// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"ordersapi/internal/domain"
)

// Token JWT + usuario autenticado.
type AuthPayload struct {
	Token string       `json:"token"`
	User  *domain.User `json:"user"`
}

type CreateOrderInput struct {
	Items []*OrderItemInput `json:"items"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type OrderItemInput struct {
	ProductID string `json:"productId"`
	Quantity  int    `json:"quantity"`
}

type OrderPage struct {
	Items    []*domain.Order `json:"items"`
	Page     int             `json:"page"`
	PageSize int             `json:"pageSize"`
	Total    int             `json:"total"`
}

type ProductPage struct {
	Items    []*domain.Product `json:"items"`
	Page     int               `json:"page"`
	PageSize int               `json:"pageSize"`
	Total    int               `json:"total"`
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
