package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"time"

	"ordersapi/internal/delivery/graphql/dataloader"
	"ordersapi/internal/delivery/graphql/generated"
	"ordersapi/internal/delivery/graphql/model"
	"ordersapi/internal/domain"
	"ordersapi/internal/usecase"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	token, user, err := r.AuthUC.Register(ctx, input.Email, input.Password)
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return &model.AuthPayload{Token: token, User: user}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	token, user, err := r.AuthUC.Login(ctx, input.Email, input.Password)
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return &model.AuthPayload{Token: token, User: user}, nil
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*domain.Order, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	items := make([]usecase.OrderItemInput, 0, len(input.Items))
	for _, it := range input.Items {
		items = append(items, usecase.OrderItemInput{ProductID: it.ProductID, Quantity: it.Quantity})
	}
	order, err := r.OrderUC.Create(ctx, userID, items)
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return order, nil
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, id string) (*domain.Order, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	order, err := r.OrderUC.Cancel(ctx, userID, id)
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return order, nil
}

// User is the resolver for the user field.
func (r *orderResolver) User(ctx context.Context, obj *domain.Order) (*domain.User, error) {
	// Vía DataLoader: las cargas de usuario de la misma petición se agrupan en
	// una sola consulta (evita N+1).
	loaders := dataloader.For(ctx)
	if loaders == nil {
		return nil, toGraphQLError(errors.New("dataloaders no inicializados en el context"))
	}
	user, err := loaders.UserByID.Load(ctx, obj.UserID)
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return user, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *orderResolver) CreatedAt(ctx context.Context, obj *domain.Order) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// Product is the resolver for the product field.
func (r *orderItemResolver) Product(ctx context.Context, obj *domain.OrderItem) (*domain.Product, error) {
	// Vía DataLoader: las cargas de producto de la misma petición se agrupan en
	// una sola consulta (evita N+1).
	loaders := dataloader.For(ctx)
	if loaders == nil {
		return nil, toGraphQLError(errors.New("dataloaders no inicializados en el context"))
	}
	product, err := loaders.ProductByID.Load(ctx, obj.ProductID)
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return product, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, filter *domain.ProductFilter, page *int, pageSize *int) (*model.ProductPage, error) {
	if _, err := requireUser(ctx); err != nil {
		return nil, err
	}
	var f domain.ProductFilter
	if filter != nil {
		f = *filter
	}
	res, err := r.ProductUC.List(ctx, f, intOr(page, 0), intOr(pageSize, 0))
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return &model.ProductPage{Items: res.Items, Total: res.Total, Page: res.Page, PageSize: res.PageSize}, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*domain.Product, error) {
	if _, err := requireUser(ctx); err != nil {
		return nil, err
	}
	product, err := r.ProductUC.Get(ctx, id)
	if err != nil {
		if errors.Is(err, domain.ErrProductNotFound) {
			return nil, nil // el campo es nullable: null si no existe
		}
		return nil, toGraphQLError(err)
	}
	return product, nil
}

// MyOrders is the resolver for the myOrders field.
func (r *queryResolver) MyOrders(ctx context.Context, page *int, pageSize *int) (*model.OrderPage, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.OrderUC.ListByUser(ctx, userID, intOr(page, 0), intOr(pageSize, 0))
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return &model.OrderPage{Items: res.Items, Total: res.Total, Page: res.Page, PageSize: res.PageSize}, nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*domain.Order, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	order, err := r.OrderUC.GetByID(ctx, userID, id)
	if err != nil {
		if errors.Is(err, domain.ErrOrderNotFound) {
			return nil, nil // nullable: null si no existe
		}
		return nil, toGraphQLError(err) // ErrOrderNotOwned -> FORBIDDEN
	}
	return order, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *domain.User) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Order returns generated.OrderResolver implementation.
func (r *Resolver) Order() generated.OrderResolver { return &orderResolver{r} }

// OrderItem returns generated.OrderItemResolver implementation.
func (r *Resolver) OrderItem() generated.OrderItemResolver { return &orderItemResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type (
	mutationResolver  struct{ *Resolver }
	orderResolver     struct{ *Resolver }
	orderItemResolver struct{ *Resolver }
	queryResolver     struct{ *Resolver }
	userResolver      struct{ *Resolver }
)
